markdown: rdiscount
permalink: pretty
pygments: true
auto: true
server: true
paginate: 3
permalink: /:year/:month/:title

sitename: lechoo.github.io
author :
 name: lechoo
 email: lechoo2u@gmail.com
 github: lechoo
 twitter: lechoo
 disqus: lechoo
